name: Demo - Workflow rodando apenas em production
on: 
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  deploy:
    needs: [run-tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app
        run: echo "Building app..."

      - name: Deploy to production
        run: echo "Deploying to production..."